Repository go-kratos/aegis, pull requests merged in 2025-07, with the labels that each got.

#40 fix: the Ceil method rounding calculations
  ratelimit/bbr/bbr.go
Labels: size:XS, lgtm

#47 add key limiter
  go.mod
  go.sum
  internal/syncmap/syncmap.go
  ratelimit/key/key.go
  ratelimit/key/key_test.go
Labels: size:L

#49 fix limit required
  ratelimit/key/key.go
  ratelimit/key/key_test.go
Labels: size:S
